[[main]]
  identifier = "Home"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "Note"
  name = "Note"
  url = "note"
  weight = 2

[[main]]
  identifier = "Archive"
  name = "Archive"
  url = "archive"
  weight = 3

[[main]]
  identifier = "File"
  name = "File"
  url = "https://ning.su/admin/files/var/www/yale.ga/"
  weight = 4

[[main]]
  identifier = "Doc"
  name = "Doc"
  url = "https://themes.gohugo.io/theme/hugo-theme-zzo/en"
  weight = 5